apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aegis.fullname" . }}-config
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
data:
  aegis.config.js: |
{{ .Values.config | indent 4 }}
{{- if .Values.soul }}
  SOUL.md: |
{{ .Values.soul | indent 4 }}
{{- end }}
