{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.fullname" . }}-secrets
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
